// Test-friendly version of main functions
// This file contains only the functions we want to unit test, 
// without the main() function and FreeRTOS task code

extern "C" {
#include "stm32l4xx_hal.h"
}

// Include memory mock for RCC testing
#include "stm32_memory_mock.h"

extern "C" {

// Initialize GPIO for LED
void GPIO_Init(void) {
    __HAL_RCC_GPIOB_CLK_ENABLE();

    GPIO_InitTypeDef gpio{};
    gpio.Pin = GPIO_PIN_3;
    gpio.Mode = GPIO_MODE_OUTPUT_PP;
    gpio.Pull = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &gpio);
}

// the function SystemClock_Config is usually auto-generated by STM32CubeMX
// Here we provide a dummy implementation for completeness
void SystemClock_Config(){
    // Empty implementation for testing
}

}
